name: Release

on:
  push:
    tags:
      - "[0-9]*"

jobs:
  package:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and release
        uses: BigWigsMods/packager@v2
